export const GET_FETCHED_FEED = "GET_FETCHED_FEED";
export const SET_SELECTED_EPISODE = "SET_SELECTED_EPISODE";
export const SET_PLAYING_EPISODE = "SET_PLAYING_EPISODE";
export const SET_ISPLAYING_STATE = "SET_ISPLAYING_STATE";
